server:
  port: 8082

spring:
  application:
    name: citizen-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:citizen_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  kafka:
    listener:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
